
namespace SemanticImageSearchAIPCT.UI.Tokenizer
{
    public static class Constants
    {
        public static readonly Dictionary<string, string> LANGUAGES = new Dictionary<string, string>
        {
            { "en", "english" },
            { "zh", "chinese" },
            { "de", "german" },
            { "es", "spanish" },
            { "ru", "russian" },
            { "ko", "korean" },
            { "fr", "french" },
            { "ja", "japanese" },
            { "pt", "portuguese" },
            { "tr", "turkish" },
            { "pl", "polish" },
            { "ca", "catalan" },
            { "nl", "dutch" },
            { "ar", "arabic" },
            { "sv", "swedish" },
            { "it", "italian" },
            { "id", "indonesian" },
            { "hi", "hindi" },
            { "fi", "finnish" },
            { "vi", "vietnamese" },
            { "he", "hebrew" },
            { "uk", "ukrainian" },
            { "el", "greek" },
            { "ms", "malay" },
            { "cs", "czech" },
            { "ro", "romanian" },
            { "da", "danish" },
            { "hu", "hungarian" },
            { "ta", "tamil" },
            { "no", "norwegian" },
            { "th", "thai" },
            { "ur", "urdu" },
            { "hr", "croatian" },
            { "bg", "bulgarian" },
            { "lt", "lithuanian" },
            { "la", "latin" },
            { "mi", "maori" },
            { "ml", "malayalam" },
            { "cy", "welsh" },
            { "sk", "slovak" },
            { "te", "telugu" },
            { "fa", "persian" },
            { "lv", "latvian" },
            { "bn", "bengali" },
            { "sr", "serbian" },
            { "az", "azerbaijani" },
            { "sl", "slovenian" },
            { "kn", "kannada" },
            { "et", "estonian" },
            { "mk", "macedonian" },
            { "br", "breton" },
            { "eu", "basque" },
            { "is", "icelandic" },
            { "hy", "armenian" },
            { "ne", "nepali" },
            { "mn", "mongolian" },
            { "bs", "bosnian" },
            { "kk", "kazakh" },
            { "sq", "albanian" },
            { "sw", "swahili" },
            { "gl", "galician" },
            { "mr", "marathi" },
            { "pa", "punjabi" },
            { "si", "sinhala" },
            { "km", "khmer" },
            { "sn", "shona" },
            { "yo", "yoruba" },
            { "so", "somali" },
            { "af", "afrikaans" },
            { "oc", "occitan" },
            { "ka", "georgian" },
            { "be", "belarusian" },
            { "tg", "tajik" },
            { "sd", "sindhi" },
            { "gu", "gujarati" },
            { "am", "amharic" },
            { "yi", "yiddish" },
            { "lo", "lao" },
            { "uz", "uzbek" },
            { "fo", "faroese" },
            { "ht", "haitian creole" },
            { "ps", "pashto" },
            { "tk", "turkmen" },
            { "nn", "nynorsk" },
            { "mt", "maltese" },
            { "sa", "sanskrit" },
            { "lb", "luxembourgish" },
            { "my", "myanmar" },
            { "bo", "tibetan" },
            { "tl", "tagalog" },
            { "mg", "malagasy" },
            { "as", "assamese" },
            { "tt", "tatar" },
            { "haw", "hawaiian" },
            { "ln", "lingala" },
            { "ha", "hausa" },
            { "ba", "bashkir" },
            { "jw", "javanese" },
            { "su", "sundanese" },
        };

        public static readonly Dictionary<string, string> TO_LANGUAGE_CODE = new Dictionary<string, string>
        {
            { "english", "en" },
            { "chinese", "zh" },
            { "german", "de" },
            { "spanish", "es" },
            { "russian", "ru" },
            { "korean", "ko" },
            { "french", "fr" },
            { "japanese", "ja" },
            { "portuguese", "pt" },
            { "turkish", "tr" },
            { "polish", "pl" },
            { "catalan", "ca" },
            { "dutch", "nl" },
            { "arabic", "ar" },
            { "swedish", "sv" },
            { "italian", "it" },
            { "indonesian", "id" },
            { "hindi", "hi" },
            { "finnish", "fi" },
            { "vietnamese", "vi" },
            { "hebrew", "he" },
            { "ukrainian", "uk" },
            { "greek", "el" },
            { "malay", "ms" },
            { "czech", "cs" },
            { "romanian", "ro" },
            { "danish", "da" },
            { "hungarian", "hu" },
            { "tamil", "ta" },
            { "norwegian", "no" },
            { "thai", "th" },
            { "urdu", "ur" },
            { "croatian", "hr" },
            { "bulgarian", "bg" },
            { "lithuanian", "lt" },
            { "latin", "la" },
            { "maori", "mi" },
            { "malayalam", "ml" },
            { "welsh", "cy" },
            { "slovak", "sk" },
            { "telugu", "te" },
            { "persian", "fa" },
            { "latvian", "lv" },
            { "bengali", "bn" },
            { "serbian", "sr" },
            { "azerbaijani", "az" },
            { "slovenian", "sl" },
            { "kannada", "kn" },
            { "estonian", "et" },
            { "macedonian", "mk" },
            { "breton", "br" },
            { "basque", "eu" },
            { "icelandic", "is" },
            { "armenian", "hy" },
            { "nepali", "ne" },
            { "mongolian", "mn" },
            { "bosnian", "bs" },
            { "kazakh", "kk" },
            { "albanian", "sq" },
            { "swahili", "sw" },
            { "galician", "gl" },
            { "marathi", "mr" },
            { "punjabi", "pa" },
            { "sinhala", "si" },
            { "khmer", "km" },
            { "shona", "sn" },
            { "yoruba", "yo" },
            { "somali", "so" },
            { "afrikaans", "af" },
            { "occitan", "oc" },
            { "georgian", "ka" },
            { "belarusian", "be" },
            { "tajik", "tg" },
            { "sindhi", "sd" },
            { "gujarati", "gu" },
            { "amharic", "am" },
            { "yiddish", "yi" },
            { "lao", "lo" },
            { "uzbek", "uz" },
            { "faroese", "fo" },
            { "haitian", "ht" },
            { "pashto", "ps" },
            { "turkmen", "tk" },
            { "nynorsk", "nn" },
            { "maltese", "mt" },
            { "sanskrit", "sa" },
            { "luxembourgish", "lb" },
            { "myanmar", "my" },
            { "tibetan", "bo" },
            { "tagalog", "tl" },
            { "malagasy", "mg" },
            { "assamese", "as" },
            { "tatar", "tt" },
            { "hawaiian", "haw" },
            { "lingala", "ln" },
            { "hausa", "ha" },
            { "bashkir", "ba" },
            { "javanese", "jw" },
            { "sundanese", "su" },
            { "burmese", "my" },
            { "valencian", "ca" },
            { "flemish", "nl" },
            { "letzeburgesch", "lb" },
            { "pushto", "ps" },
            { "panjabi", "pa" },
            { "moldavian", "ro" },
            { "moldovan", "ro" },
            { "sinhalese", "si" },
            { "castilian", "es" },
        };

        public const string EndOfText = "<|endoftext|>";

        public const string StartofTranscript = "<|startoftranscript|>";

        public const string Translate = "<|translate|>";

        public const string Transcribe = "<|transcribe|>";

        public const string Startoflm = "<|startoflm|>";

        public const string StartofPrev = "<|startofprev|>";

        public const string Nospeech = "<|nospeech|>";

        public const string NotimeStamps = "<|notimestamps|>";

        public static readonly int[] NON_SPEECH_TOKENS = new int[]
         {
                    1, 2, 7, 8, 9, 10, 14, 25, 26, 27, 28, 29, 31, 58, 59, 60, 61, 62, 63, 90, 91, 92, 93,
                    357, 366, 438, 532, 685, 705, 796, 930, 1058, 1220, 1267, 1279, 1303, 1343, 1377, 1391,
                    1635, 1782, 1875, 2162, 2361, 2488, 3467, 4008, 4211, 4600, 4808, 5299, 5855, 6329, 7203,
                    9609, 9959, 10563, 10786, 11420, 11709, 11907, 13163, 13697, 13700, 14808, 15306, 16410,
                    16791, 17992, 19203, 19510, 20724, 22305, 22935, 27007, 30109, 30420, 33409, 34949, 40283,
                    40493, 40549, 47282, 49146, 50257, 50357, 50358, 50359, 50360, 50361
         };
    }
}
